(() => {
 const data={
  central:{title:'Central Park',copy:'Step into a living garden at sea — over ten thousand real plants, trees, and vines thriving eight decks above the ocean. Wander winding pathways to candlelit dinners, sip handcrafted cocktails beneath the canopy, and catch live musicians as the stars come out. It is the most magical (and most surprising) place on the entire ship.',image:'central-park.jpg',venues:[['150 Central Park','Specialty dining','The most elegant table at sea — a chef-driven menu with herbs picked from the garden right outside the door.'],["Jamie’s Italian",'Specialty dining','Jamie Oliver\'s rustic pastas made fresh daily — get the truffle tagliatelle and thank us later.'],['Trellis Bar','Bar','Craft cocktails under real trees and twinkling lights — the dreamiest pre-dinner stop on the ship.'],['Chops Grille','Specialty dining','Sizzling dry-aged steaks and a legendary mushroom soup — a Royal Caribbean classic for a reason.']]},
  pool:{title:'Pool Deck',copy:'This is where the party lives! Splash between pools and bubbling whirlpools, race down the Perfect Storm waterslides, claim a lounger in the sun, and let the pool band and frozen drinks carry you straight into vacation mode — all with endless ocean views in every direction.',image:'pool-deck.jpg',venues:[['Main Pool','Included','The beating heart of sea days — live bands, cannonballs, and sunshine from breakfast to golden hour.'],['Solarium','Included','A glass-canopied, adults-only oasis with serene pools and bubbling loungers. Blissfully cannonball-free.'],['Perfect Storm','Included','Three stories of twisting, racing waterslides! Challenge someone to ride the Typhoon and Cyclone side by side — the drop is real, the bragging rights are forever.'],['Pool Bars','Bar','A frozen Miami Vice in one hand, ocean breeze in the other. Vacation: officially achieved.']]},
  entertainment:{title:'Entertainment Place',copy:'Broadway-caliber productions, professional ice-skating spectaculars, live comedy, and full theatrical stage shows — every single night. The hardest part of your evening will be choosing which jaw-dropping performance to see first. Arrive early; these shows fill up for a reason!',image:'entertainment.jpg',venues:[['Royal Theater','Entertainment','A full Broadway production of Grease plus dazzling original shows — West End quality, zero ticket price.'],['Studio B','Entertainment','Professional figure skaters spinning and soaring on real ice — in the middle of the Caribbean. See it to believe it.'],['Comedy Live','Entertainment','Late-night stand-up in an intimate club. Big laughs, adult humor — arrive early, seats go fast.']]},
  boardwalk:{title:'Boardwalk',copy:'Pure boardwalk nostalgia with a wow factor: ride a hand-carved carousel, grab hot dogs and milkshakes, then watch Olympic-level divers plunge ten stories into the AquaTheater pool as the sun sets behind them. Fun by day, absolutely unforgettable by night.',image:'boardwalk.jpg',venues:[['AquaTheater','Entertainment','Olympic-caliber divers plunging ten stories into the deepest pool at sea, with acrobats and dancing fountains — the ship\'s signature jaw-dropper.'],['Carousel','Included','A full-size, hand-carved carousel... on a cruise ship. Yes, really — and riding it never gets old.'],['Boardwalk Dog House','Included dining','Gourmet hot dogs and bratwurst, free and fast — the perfect refuel between adventures.'],['Johnny Rockets','Specialty dining','Retro diner burgers, hand-spun shakes, and waiters who break into dance routines.']]},
  promenade:{title:'Royal Promenade',copy:'The buzzing main street of the ship — a glittering indoor boulevard lined with cafés, duty-free shopping, and bars where the music never seems to stop. Time it right and a full-blown parade will march past your table. Grab a coffee, find a bench, and watch the whole ship stroll by.',image:'promenade.jpg',venues:[['Café Promenade','Included dining','Coffee, sandwiches, and cookies around the clock — your anytime fuel stop, always included.'],["Sorrento’s",'Included dining','Hot pizza by the slice until late — future-you, walking back from the show, will be grateful.'],['Schooner Bar','Bar','Nightly piano singalongs — request a song and watch the whole room join in.'],['Shopping','Explore','Duty-free jewelry, watches, and flash sales that appear out of nowhere — the treasure hunt is half the fun.']]},
  youth:{title:'Youth Zone',copy:'Kids may never want to leave: award-winning Adventure Ocean programming, teen-only lounges, an arcade packed with games, and new friends from all over the world. Parents get a night out; kids get the best week of their year. Everybody wins.',image:'youth-zone.jpg',venues:[['Adventure Ocean','Included','Award-winning, age-grouped programming so fun the kids will beg to go back — science labs, games, and themed parties.'],['Teen Spaces','Included','Teens-only lounges and a no-parents-allowed nightclub where friendships form fast (that\'s the point).'],['Arcade','Activity','Racing sims, claw machines, and air hockey — rivalry headquarters for the whole family.'],['Family Activities','Included','Scavenger hunts, game shows, and poolside competitions the whole crew can win together.']]},
  spa:{title:'Vitality Spa',copy:'Your serene escape above the sea — melt into a massage, unwind in the thermal suite, take a sunrise yoga class, or hit the ocean-view fitness center. Come aboard for the celebration, leave feeling like a brand-new person.',image:'vitality-spa.jpg',venues:[['Vitality Spa','Specialty','Massages, facials, and a heated thermal suite with endless ocean views — pure post-pickleball bliss.'],['Fitness Center','Included','A full gym with the best view of any workout you\'ll ever do — sunrise spin over open water.'],['Salon','Specialty','Blowouts, manicures, and celebration-day glam — book early, the chairs fill up.'],['Wellness Classes','Activity','Sunrise yoga on the sea, meditation, and stretch classes to balance out the buffet.']]}
 };
 const title=document.querySelector('#n-title'),copy=document.querySelector('#n-copy'),image=document.querySelector('#n-image'),heading=document.querySelector('#venue-heading'),cards=document.querySelector('#venue-cards');
 function show(key){const x=data[key]; title.textContent=x.title; copy.textContent=x.copy; image.src=`assets/neighborhoods/${x.image}`; image.alt=`${x.title} on Harmony of the Seas`; heading.textContent=`Venues in ${x.title}`; cards.innerHTML=x.venues.map(v=>`<article><span>${v[1]}</span><h3>${v[0]}</h3><p>${v[2]}</p></article>`).join(''); document.querySelectorAll('.neighborhood').forEach(b=>b.classList.toggle('active',b.dataset.neighborhood===key));}
 document.querySelectorAll('.neighborhood').forEach(b=>b.addEventListener('click',()=>{show(b.dataset.neighborhood);if(window.matchMedia('(max-width:760px)').matches){var p=document.getElementById('neighborhood-panel');if(p)p.scrollIntoView({behavior:'smooth',block:'start'});}})); show('central');
 const stage=document.querySelector('#ship-interactive'),img=stage.querySelector('img'); let scale=1,rx=0,ry=0,down=false,x0=0,y0=0;
 const draw=()=>img.style.transform=`scale(${scale}) rotateX(${ry}deg) rotateY(${rx}deg)`;
 stage.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(1,Math.min(2.2,scale+(e.deltaY<0?.12:-.12)));draw()},{passive:false});
 stage.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')return;if(e.target.closest('.neighborhood'))return;down=true;x0=e.clientX;y0=e.clientY;});stage.addEventListener('pointermove',e=>{if(!down)return;rx=Math.max(-16,Math.min(16,rx+(e.clientX-x0)*.08));ry=Math.max(-9,Math.min(9,ry-(e.clientY-y0)*.05));x0=e.clientX;y0=e.clientY;draw()});['pointerup','pointercancel','pointerleave'].forEach(evt=>stage.addEventListener(evt,()=>down=false));
})();
